# Generated by Django 5.1.5 on 2026-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimusic', '0005_remove_song_audio_url_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Посилання (YouTube, Spotify тощо)'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=255, verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва пісні'),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рік'),
        ),
    ]
