# Generated by Django 5.1.5 on 2026-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimusic', '0007_playlist_is_public_playlist_likes_alter_song_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Playlist Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=255, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Song Title'),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
